apiVersion: v1
kind: Service
metadata:
  name: webnodb
spec:
  selector:
    app: webnodb
  ports:
    - protocol: TCP
      port: 80  # External port exposed by the service
      targetPort: 5000  # Flask container port
  type: ClusterIP
