flaskApp:
  replicas: 3
  image: amelique/docker-flask_app:latest
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

mongodb:
  image: mongo:latest
  port: 27017
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

ingress:
  enabled: true
  host:
    webnodb: "webnodb.aleconte.net4255.luxbulb.org"
    webdb: "webdb.aleconte.net4255.luxbulb.org"

service:
  port: 8080

serviceAccount:
  create: true

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
