image:
  repository: amelique/amelique
  tag: latest
  pullPolicy: IfNotPresent

flaskApp:
  replicas: 3
  image: amelique/amelique:latest
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

mongodb:
  image: mongo:latest
  port: 27017
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

webnodb:
  image: "amelique/docker-flask_app:latest"  
  replicas: 3


ingress:
  enabled: true
  host:
    webnodb: "webnodb.aleconte.net4255.luxbulb.org"
    webdb: "webdb.aleconte.net4255.luxbulb.org"

service:
  port: 8080


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
