version: '3.1'

services:

  mongo:
    image: mongo:4.0.13-xenial
    container_name: mongodb_container
    restart: always
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
