apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.flaskApp.replicas }}
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
        - name: webdb
          image: {{ .Values.flaskApp.image }}
          resources:
            requests:
              memory: {{ .Values.flaskApp.resources.requests.memory }}
              cpu: {{ .Values.flaskApp.resources.requests.cpu }}
            limits:
              memory: {{ .Values.flaskApp.resources.limits.memory }}
              cpu: {{ .Values.flaskApp.resources.limits.cpu }}
          ports:
            - containerPort: 5000
